In [1]:
import numpy as np
from sklearn.model_selection import KFold
import json

In [11]:
X = ["a", "b", "c", "d", "x", "y","2","ds","s"]
kf = KFold(n_splits=3)
for train, test in kf.split(X):
    print("%s %s" % (train, test))

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [6]:
def random_split():
    tasks_sentences = []
    with open("corpus最终版\corpus_5.txt", "r", encoding='utf-8') as fp:
        for line in fp.readlines():
            lsp = line.split()
            sentence = " ".join(lsp[1:])
            tasks_sentences.append(sentence)
            

def expert_split():
    tasks_sentences = [[] for i in range(20)]
    with open("corpus最终版\corpus_5.txt", "r", encoding='utf-8') as fp:
        for line in fp.readlines():
            lsp = line.split()
            info = lsp[0]
            sentence = " ".join(lsp[1:])
            index = int(info.split(":")[4]) - 1
            tasks_sentences[index].append(sentence)
            
            
def bundle_split():
    tasks_sentences = [[] for i in range(920)]
    with open("corpus最终版\corpus_5.txt", "r", encoding='utf-8') as fp:
        for line in fp.readlines():
            lsp = line.split()
            info = lsp[0]
            sentence = " ".join(lsp[1:])
            index = int(info.split(":")[1]) - 1
            tasks_sentences[index].append(sentence)
            
            
def table_split():
    tasks_sentences = [[] for i in range(37)]
    with open("corpus最终版\corpus_5.txt", "r", encoding='utf-8') as fp:
        for line in fp.readlines():
            lsp = line.split()
            info = lsp[0]
            sentence = " ".join(lsp[1:])
            index = int(info.split(":")[3]) - 1
            tasks_sentences[index].append(sentence)

In [7]:
tasks_sentences = []
with open("corpus最终版\corpus_5.txt", "r", encoding='utf-8') as fp:
    for line in fp.readlines():
        lsp = line.split()
        sentence = " ".join(lsp[1:])
        tasks_sentences.append(sentence)
len(tasks_sentences)

14035

In [26]:
class tet(object):
    def __init__(self):
        pass
    
   
        
    def prp(self):
        print("prp")
        tet.sdd()
        self.sss()
        print("aasss")
        
    def sdd():
        print("sdd")
        
    
    def sss(self):
        print("sss")

In [27]:
ttt = tet()
ttt.prp()

prp
sdd
sss
aasss


In [75]:
a=[[[1,2],[3,5]],[[6,[5,7,8]],[10,1]]]


In [76]:
np.random.shuffle(a)
a

[[[6, [5, 7, 8]], [10, 1]], [[1, 2], [3, 5]]]

In [91]:
a = [[1,2],[3,5]]
b = np.array(a)

In [93]:
b += np.array([8,10])

In [94]:
b

array([[ 9, 12],
       [11, 15]])

In [89]:
b = [[1,2],[3,5,8]]
np.asarray(b),np.asarray(b).shape

(array([list([1, 2]), list([3, 5, 8])], dtype=object), (2,))

In [90]:
a

[[1, 2], [3, 5, 8]]

In [95]:
Y = np.array([[1, 2], [3, 4], [5, 6], [7, 8],[9,10],[11,12]])
#y = np.array([1, 2, 3, 4])
i=0
kf = KFold(n_splits=3)
#3折交叉验证，将数据分为3份，每次取一份作为test集
for train_index, test_index in kf.split(Y):
    i=i+1
    print(i)
    print('train_index', train_index, 'test_index', test_index)
    #train_index与test_index为下标
    train_Y = Y[train_index]
    test_Y= Y[test_index]
    print("train_Y",train_Y)
    print("test_Y",test_Y)

1
train_index [2 3 4 5] test_index [0 1]
train_Y [[ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
test_Y [[1 2]
 [3 4]]
2
train_index [0 1 4 5] test_index [2 3]
train_Y [[ 1  2]
 [ 3  4]
 [ 9 10]
 [11 12]]
test_Y [[5 6]
 [7 8]]
3
train_index [0 1 2 3] test_index [4 5]
train_Y [[1 2]
 [3 4]
 [5 6]
 [7 8]]
test_Y [[ 9 10]
 [11 12]]


In [2]:
a=np.array([[1,2],[2,3]])
b=np.array([[5,8],[8,10],[3,7]])
c = np.array([[12,7]])
d = [a,b,c]

In [109]:
d

[array([[1, 2],
        [2, 3]]), array([[ 5,  8],
        [ 8, 10],
        [ 3,  7]]), array([[12,  7]])]

In [5]:
a=0.23
b=0.366
c=8.3
print("%s, %s, %s" % (a,b,c))

0.23, 0.366, 8.3


In [9]:
split_info = {
    "random": False,
    "expert": [20, 4],
    "bundle": [920, 1],
    "table": [37, 3]
}