In [1]:
import numpy as np

In [6]:
a = np.arange(0,10)
b = np.arange(10,20)
c = np.arange(20,30)
a,b,c

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),
 array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29]))

In [12]:
a = np.arange(0,10)
np.random.shuffle(a)
a

array([4, 0, 8, 9, 7, 5, 6, 1, 2, 3])

array([9, 6, 8, 1, 2, 3, 7, 4, 0, 5])

In [1]:
import numpy as np
import pandas as pd
import nltk

In [4]:
corpus_xk = pd.read_excel("corpus_xk.xlsx")

In [5]:
corpus_xk

interviewee task                                           sentence  \
0           WJC    1  What is the popularity of Arkansas on July 1st...   
1           WJC    1                       Where is Harvard University?   
2           WJC    1  How many faculties are there in Harvard Univer...   
3           WJC    1            What is the type of Harvard University?   
4           WJC    2       which county has more than 30000 popularity?   
..          ...  ...                                                ...   
504         ZJH    6  Can you tell me what the range of students' sc...   
505         ZJH    7  Does this table show anything about the distri...   
506         ZJH    8  Which student didn't do as well as expected in...   
507         ZJH    9  Is there any obvious clustering of students' w...   
508         ZJH   10  Does a student's grade have anything to do wit...   

                            data related                   table  \
0    popularity, Arkansas, July 1st 2002        co-est2002-01-05   
1                     Harvard University  top-50-us-universities   
2          faculties, Harvard Universtiy  top-50-us-universities   
3               Harvard University, type  top-50-us-universities   
4               county, 30000 popularity        co-est2002-01-05   
..                                   ...                     ...   
504                 students' score, CW2                     NaN   
505                     F grade students                     NaN   
506                  student, final exam                     NaN   
507                     students' weight                     NaN   
508                student's grade, city                     NaN   

                  note  
0                  NaN  
1    where 表示 location  
2                  NaN  
3                  NaN  
4                  NaN  
..                 ...  
504                NaN  
505                NaN  
506                NaN  
507                NaN  
508                NaN  

[509 rows x 6 columns]

In [33]:
509 - 490

19

In [7]:
corpus_xk.dtypes

interviewee     object
task            object
sentence        object
data related    object
table           object
note            object
dtype: object

In [15]:
corpus_xk.iloc[0].sentence, type(corpus_xk.iloc[0]),corpus_xk.iloc[0].task,type(corpus_xk.iloc[0].task)

('What is the popularity of Arkansas on July 1st 2002?',
 pandas.core.series.Series,
 1,
 int)

In [30]:
corpus_xk[(corpus_xk.task == '2') | (corpus_xk.task == 2)].sentence

4           which county has more than 30000 popularity?
5                       which university is in New York?
6      which university has more than 30 faculties an...
7      which county has less than 2000 popularity in ...
48     How many countries whoes happiness score is gr...
49     Which region has the most countries of happine...
50                    How many students get the A grade?
51               Select all CW1 score not less than 80%.
91                          Find all qualified students.
92                    Find out the neighboors of node A.
93                              Which team won the game?
94     In which country does the number of female is ...
129    Show me a country with a low economy but high ...
138    What countries have a higher happiness score t...
139    Show me all countries with a higher happiness ...
140    Please find all countries which have similar h...
167                   Collect books published this year.
172                What are fic

In [31]:
corpus_xk[corpus_xk["task"].str.contains('1', case=False, na=False)]

interviewee task                                           sentence  \
44          ZKJ    1             What is the happiness rank of Iceland?   
45          ZKJ    1   How many dimensions to describe happiness score?   
46          ZKJ    1            How many students in the grade records?   
47          ZKJ    1               Show me Kibo Mcgee's mid-term score.   
81          ZKJ   10  Can we infer that higher freedom lead to highe...   
82          ZKJ   10  Is the countries has higher trust score get th...   
83          ZKJ   10                  Who get the greatest progression?   
84          ZKJ   10        Is any teachers lead to the greater grades?   
87           XX    1                  What is the revenue of "Titanic"?   
88           XX    1   How many goals does Liverpool score in the game?   
89           XX    1          Find the score of course A for student B.   
90           XX    1  How long would it take from location A to loca...   
115          XX   10  What is the correlation between the release ye...   
116          XX   10  Are the release year and the revenue positivel...   
117          XX   10                   Does a higher A mean a larger B?   
118          XX   10  Is it true that young students are more likely...   
130          WJ   10  Find out the relationship between happiness sc...   
131          WJ   10  How economy or something else affect happiness...   
458         ZJH   10  Does life expectancy have some relation with t...   
460         ZJH   10  Can you tell me the tendency of the number of ...   

                           data related                        table  \
44              happiness rank, Iceland  World Happiness Report 2015   
45          happiness score, dimensions  World Happiness Report 2015   
46                      students, grade                grade-records   
47           Kibo Mcgee, mid-term score                grade-records   
81                   freedom, happiness  World Happiness Report 2015   
82         trust score, happiness score  World Happiness Report 2015   
83                          progression                grade-records   
84                     teachers, grades                grade-records   
87                     revenue, Titanic                          NaN   
88               goals, Liverpool, game                          NaN   
89           score, course A, student B                          NaN   
90               location A, location B                          NaN   
115               release year, revenue                          NaN   
116               release year, revenue                          NaN   
117                                 NaN                          NaN   
118                    students, wechat                          NaN   
130                     happiness score  World Happiness Report 2015   
131            economy, happiness score  World Happiness Report 2015   
458            life expectancy, smokers                          NaN   
460  vehicles, Japan, Korea, 2000, 2010                          NaN   

                                                  note  
44                                                 NaN  
45                                                 NaN  
46                                                 NaN  
47                                                 NaN  
81                                                 NaN  
82                                                 NaN  
83                     Who 指的是学生, progression指的是分数提高很多  
84                                                 NaN  
87                                                 NaN  
88                                                 NaN  
89                                                 NaN  
90                                                 NaN  
115                                                NaN  
116                                                NaN  
117                                                NaN  
118